version: '3.9'

volumes: 
    db_data:

services:
  app:
    image: kyoto
    container_name: kyoto
    restart: unless-stopped
    build:
      context: .
    ports:
      - "0.0.0.0:8084:8080"
    depends_on:
      - db
    command: ["dotnet", "Kyoto.dll"]
  db:
    container_name: kyoto-db
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: oolxg
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: KyotoDatabase
    volumes:
      - db_data:/var/lib/postgresql/data/
    expose:
      - 5432
  
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    container_name: kyoto-backups
    restart: unless-stopped
    volumes:
      - ~/kyoto_db_backups:/backups
    links:
      - db:db
    depends_on: 
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: KyotoDatabase
      POSTGRES_USER: oolxg
      POSTGRES_PASSWORD: 12345678
      SCHEDULE: "@hourly"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 2
        